Replace URL with String as the key
The equals() implementation of URL resolves the hostname into an IP address.
When multiple URLs are mapped into the same IP (especially with 1.1.1.1 DNS server),
it will cause the following exception:
```
java.lang.IllegalArgumentException: Multiple entries with same key
```